//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperchargedArray.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperchargedArray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma OPENCL EXTENSION cl_khr_fp64 : enable
        ///__kernel void ndarr_add_double(global double* a, global double* b, global double* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] + b[i];
        ///}
        ///
        ///__kernel void ndarr_sub_double(global double* a, global double* b, global double* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] - b[i];
        ///}
        ///
        ///__kernel void ndarr_mul_double(global double* a, global double* b, global double* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] * b[i];
        ///}
        ///
        ///__kernel  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InternalDoubleKernels {
            get {
                return ResourceManager.GetString("InternalDoubleKernels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __kernel void ndarr_add_float(global float* a, global float* b, global float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] + b[i];
        ///}
        ///
        ///__kernel void ndarr_sub_float(global float* a, global float* b, global float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] - b[i];
        ///}
        ///
        ///__kernel void ndarr_mul_float(global float* a, global float* b, global float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] * b[i];
        ///}
        ///
        ///__kernel void ndarr_div_float(global float* a, global float* b, glob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InternalFloatKernels {
            get {
                return ResourceManager.GetString("InternalFloatKernels", resourceCulture);
            }
        }
    }
}
