//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.ArrayExtension.Accelerated.Kernels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CLCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CLCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.ArrayExtension.Accelerated.Kernels.CLCode", typeof(CLCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __kernel void ndarr_add(global read_only float *a, global read_only float *b, global write_only float *r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] + b[i];
        ///}
        ///
        ///__kernel void ndarr_sub(global read_only float *a, global read_only float *b, global write_only float *r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] - b[i];
        ///}
        ///
        ///__kernel void ndarr_mul(global read_only float *a, global read_only float *b, global write_only float *r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] * b[i]; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArithmeticKernel {
            get {
                return ResourceManager.GetString("ArithmeticKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __kernel void ndarr_fill(global float *x, float value)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	x[i] = value;
        ///}
        ///
        ///__kernel void ndarr_gt(global read_only float *a, global read_only float *b, global read_only float *r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	if (a[i] &gt; b[i])
        ///		r[i] = 1;
        ///	else
        ///		r[i] = 0;
        ///}
        ///
        ///__kernel void ndarr_ge(global read_only float* a, global read_only float* b, global read_only float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	if (a[i] &gt;= b[i])
        ///		r[i] = 1;
        ///	else
        ///		r[i] = 0; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __kernel void ndarr_exp(global read_only float* x, global write_only float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = exp(x[i]);
        ///}
        ///
        ///__kernel void ndarr_log(global read_only float* x, global write_only float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = log(x[i]);
        ///}
        ///
        ///__kernel void ndarr_log1p(global read_only float* x, global write_only float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = log1p(x[i]);
        ///}
        ///
        ///__kernel void ndarr_log10(global read_only float* x, global write_only float [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LogExpPow {
            get {
                return ResourceManager.GetString("LogExpPow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __kernel void ndarr_floor(global read_only float* x, global write_only float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = floor(x[i]);
        ///}
        ///
        ///__kernel void ndarr_ceil(global read_only float* x, global write_only float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = ceil(x[i]);
        ///}
        ///
        ///__kernel void ndarr_round(global read_only float* x, global write_only float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = round(x[i]);
        ///}
        ///
        ///__kernel void ndarr_trunc(global read_only float* x, global write_only [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rounding {
            get {
                return ResourceManager.GetString("Rounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __kernel void ndarr_sin(global read_only float *x, global write_only float *r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = sin(x[i]);
        ///}
        ///
        ///__kernel void ndarr_cos(global read_only float *x, global write_only float *r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = cos(x[i]);
        ///}
        ///
        ///__kernel void ndarr_tan(global read_only float *x, global write_only float *r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = tan(x[i]);
        ///}
        ///
        ///__kernel void ndarr_arcsin(global read_only float *x, global write_only float *r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrignometryKernel {
            get {
                return ResourceManager.GetString("TrignometryKernel", resourceCulture);
            }
        }
    }
}
