//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.ArrayExtension.Accelerated.Kernels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CLCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CLCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.ArrayExtension.Accelerated.Kernels.CLCode", typeof(CLCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __kernel void ndarr_add(__global float* a, __global float* b, float *r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] + b[i];
        ///}
        ///
        ///__kernel void ndarr_sub(__global float* a, __global float* b, float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] - b[i];
        ///}
        ///
        ///__kernel void ndarr_mul(__global float* a, __global float* b, float* r)
        ///{
        ///	const int i = get_global_id(0);
        ///
        ///	r[i] = a[i] * b[i];
        ///}
        ///
        ///__kernel void ndarr_div(__global float* a, __global float* b, float* r)
        ///{
        ///	const int i = get_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArithmeticKernel {
            get {
                return ResourceManager.GetString("ArithmeticKernel", resourceCulture);
            }
        }
    }
}
